ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns=[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.cart_remove, name="cart_remove"),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),


]

ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from . import views
app_name='ecommerceapp'


urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name="prodCatDetail"),
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('credentials/', include('credentials.urls')),
    path('index/', include('ecommerceapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

ecommerceproject/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from ecommerceapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']


    def __str__(self):
        return '{}'.format(self.cart_id)



class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'


    def sub_total(self):
        return self.product.price * self.quantity


    def __str__(self):
        return '{}'.format(self.cart_id)


class Usercart(models.Model):
    cartitems = models.ForeignKey(CartItem, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    userdetails=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.User.id)

ecommerceproject/cart/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from . models import Cart,CartItem,Usercart
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
        else:
            messages.info(request,"you have selected maximum number of stocks")
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/basestyle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container-fluid">
    <div class="inside-container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    <div>
        {% include 'footer.html' %}
    </div>
</div>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}
This is a cart page proceed to review your items and place the order
{% endblock %}


{% block title %}
Cart:Guruvi Education
{% endblock %}


{% block content %}
{% if not cart_items %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title"> Your cart is empty </h1><br>
    <p class="text-center"><a href="{% url 'ecommerceapp:allProdCat' %}">Continue Shopping</a></p>
  </div>
</div>
{% else %}
<div>
  <div>
    <br><h1 class="text-center">Your Shopping Cart</h1>
  </div>
</div>
<!-- -&#45;&#45;&#45;&#45;-->
<div class="mx-auto row outerBox">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_costum_table">
        <thead class="my_costum_thead">
          <tr><th colspan="5">Your Items</th> </tr>
        </thead>
        <tbody>
          {% for cart_item in cart_items %}
          <tr>
              <td><a href="{{ cart_item.product.get_absolute_url }}"><img src="{{ cart_item.product.image.url }}" alt="image link not working" class="float-left rounded custom_image"></a> </td>
<!--              <br>-->
              <td class="float-left">{{ cart_item.product.name }}
              <br>
              SKU:{{ cart_item.product.id }}
              <br>
              Price : {{ cart_item.product.price }}
              <br>
              Quantity : {{ cart_item.quantity }}

              </td>

                {% if cart_item.quantity < cart_item.product.stock %}
              <td>
                &nbsp;<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus"></i> </a>
                &nbsp; <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa fa-minus"></i> </a>
                &nbsp; <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash"></i> </a>
              </td>
                {% else %}
              <td>
                &nbsp;<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus"></i> </a>
                &nbsp; <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fa fa-minus"></i> </a>
                &nbsp; <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash"></i> </a>
              </td>
                {% endif %}
          </tr>

          {% endfor %}
        </tbody>
      </table>

    </div>
    {% endif %}
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
<!--      <br><br>-->
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>Checkout</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>Please review before making your payment</td>
                                {{cart_data.id}}

                {% for cart_datas in cart_data %}
                {{cart_data.id}}
                {% endfor %}
            </tr>
        </tbody>
    </table>
  <div class="mx-auto btn btn-secondary"><a style="text-decoration:none;!important;color:white;" href="{% url 'ecommerceapp:allProdCat' %}">Continue Shopping</a> </div>
  </div>

</div>
<div class="container">
<div class="row">
    <div class="mx-auto text-center col-12 col-md-12 col-lg-12 col-sm-12">
    {% for msg in messages %}

      {{ msg }}

      {% endfor %}
</div>
</div>

</div>

{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to Store where you want to buy
    {% endif %}
{% endblock %}

<!--____________-->


{% block title %}
    {% if category %}
        {{ category.name }} --ABC Store
    {% else %}
        See our new collection
    {% endif %}
{% endblock %}


<!--__________________________________________________-->

{% block content %}
{% if category %}
<div>
    <div>
        <h1 style="text-transform:uppercase" class="product_head">{{ category.name }}  Courses  </h1>
<!--        <a class="" href="{% url 'ecommerceapp:allProdCat' %}"></a>-->
    </div>
</div>
{% endif %}

<!--_________________________-->


<div class="imagealign">
    {% if category %}
        <img src="{{category.image.url}}" alt="{{category.image.url}}" width="80%" height="350px" style="margin:auto auto;" class="bannerImg">
</div>
        <br>

        <div>
            <h1 style="text-transform:uppercase;" class="product_head">{{ category.name }}</h1>
            <p class="product_desc">{{ category.description }}</p>
        </div>



    {% else %}
        {% if user.is_authenticated %}
  hi. {{ request.user.username }}
  {% endif %}
        <div>
            <img class="bannerImg" src="{% static 'img/banner.png' %}" width="100%" height="520px" alt="{% static 'img/banner.jpg' %}">
        </div>
<br>
        <div>
            <h1 class="product_head">POPULAR COURSES</h1>
            <p class="product_desc text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet.", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
        </div>
    {% endif %}


<!--______________________________________- -->


<div class="container">
<div class="row">
    {% for product in products.object_list %}
    <div class="col-4 ">
        <a href="{{ product.get_url }}">
        <div class="shadow card-mec" >
                <img class="card-mec-image" src="{{ product.image.url }}" width="100px" height="150px" alt="{{ product.name }}">
                <div> <h4 class="card-mec-name">{{product.name}}</h4>  <p class="card-mec-price"><a class="fa fa-inr"></a> {{product.price}}</p>   </div>
        </div>
        </a>
    </div>
    {% endfor %}
</div>
</div>
<div class="mx-auto">
    {% if products.paginator.num_pages > 1 %}
    <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm{% if products.number == pg %} active {% endif %}">{{ pg }}</a>
        {% endfor %}
    </div>

    {% endif %}
</div>



{% endblock%}

ecommerceproject/templates/footer.html
<div class="my_footer footer navbar-fixed-bottom">
    <p> @copyright .All rights reserved </p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceapp:allProdCat' %}"> <img src="{% static 'img/logo.png' %}" alt="{% static 'img/logo.png' %}" width="150px"height="150px"class="header-logo"></a>
    </center>
</header>

ecommerceproject/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="text-center m-b-md custom-login">
                <h5>PLEASE LOG IN TO CONTINUE</h5>
                <br>
                {% for msg in messages %}
                {{ msg }}
                {% endfor %}
            </div>
        </div>
    </div>
<div class="row">
    <div class="col-md-6 col-sm-12 col-xl-4 col-lg-5 mx-auto my-auto">
    <div class="hpanel">
        <div class="panel-body">
            <form action="/index/" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" for="username">Username</label>
                    <input type="text" placeholder="example@gmail.com" title="Please enter you username" required="" value="" name="username" id="username" class="form-control">
                    <span class="help-block small">Enter your username</span>
                </div>
                <div class="form-group">
                    <label class="control-label" for="password">Password</label>
                    <input type="password" title="Please enter your password" placeholder="******" required="" value="" name="password" id="password" class="form-control">
                    <span class="help-block small">Enter a strong password</span>
                </div>
                <div class="checkbox login-checkbox">
                    <label><input type="checkbox" class="i-checks"> Remember me </label>
                    <p class="help-block small">Please Register is you don't have an account</p>
                    <div class="text-center">

                    <a href="/credentials/register/" class="btn btn-success loginbtn"/> Register </a> &nbsp;
                        <input value="Login" type="submit" class="btn btn-success loginbtn"/>

                    </div>
                    <br>
                    <br>
                </div>
            </form>
        </div>
    </div>
   </div>
</div>
{% endblock %}

ecommerceproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light text-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <img src="{% static 'img/logo.png' %}" alt="{% static 'img/logo.png' %}" width="30px" height="30px">
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'ecommerceapp in request.path' %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All Courses</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>
          {% endfor %}


          <div class="dropdown-divider"></div>
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{ item_count }})</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0"action="{% url 'search_app:SearchResult' %}">
      <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-info my-2 my-sm-0 last-button" type="submit"><i class="fa fa-search"></i></button>
    </form>
    {% if login %}
    hi

    {% else %}

    <a href="{% url 'login' %}" class="btn btn-info">Login</a>
    {% endif %}
  </div>

</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}



{% block title%}
{% if category %}
    {{ product.name }}-Abc Store
{% endif %}
{% endblock %}

{% block content %}


<div>
    <div>
        <p> <a href="{{'ecommerceapp:allProdCat' }}">Home</a>| <a href="{{ product.category.get_url }}">{{ product.category }}</a>|{{ product.name }} </p>
    </div>
</div>


<div class="container ">
    <div class="product_preview">
    <div class="row">

        <div class="col-5">
            <div>
            <img src="{{ product.image.url }}"width="200px" height="200px" alt="{{ product.name }}">
            </div>
        </div>
        <div class="col-7">
            <div>
                <h1>{{ product.name }}</h1>
                <p><a class="fa fa-inr"></a>  {{ product.price }}</p>
                <p>{{ product.description }}</p>
                {% if product.stock <= 0 %}
                    <p><b>Out Of Stock</b></p>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                {% endif %}
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

ecommerceproject/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12"></div>
            <div class="col-md-6 col-md-6 col-sm-6 col-xs-12">
                <div class="text-center custom-login">
                    <h3>Registration</h3>
                </div>
                <br>
                <div class="hpanel">
                    <div class="panel-body">
                        <form action="/credentials/register/" method ="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group col-lg-12">
                                    <label>Username</label>
                                    <input type="text" name="username" class="form-control">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label> Name</label>
                                    <input type="text" name="firstname" class="form-control">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Email Address</label>
                                    <input type="email" name="email" class="form-control">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Password</label>
                                    <input type="password" name="password" class="form-control">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Repeat Password</label>
                                    <input type="password"name="cpassword" class="form-control ">
                                </div>
                                <div class="checkbox col-lg-12">
                                    <input type="checkbox" class="i-checks" checked> Remember me.
                                </div>
                            </div>
                            <br><br>
                            <div class="text-center">
                                <a><input value="Register" type="submit" class="btn btn-info"/> </a>&nbsp;&nbsp;
                                <a class="btn btn-info" href="/credentials/login">Login</a>

                            </div>
                        </form>
                        <br><br>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12"></div>
        </div>
    </div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
We provie variety of courses
{% endblock %}

{% block title %}
Search
{% endblock %}

{% block content %}
<div class="">
    <p class="text-center my_search_text">You have searched for : <b>{{ querry }}</b></p>
</div>

<div class="container">
<div class="row">
    {% for product in products %}
    <div class="col-4 ">
        <a href="{{ product.get_url }}">
        <div class="shadow card-mec" >
                <img class="card-mec-image" src="{{ product.image.url }}" width="100px" height="150px" alt="{{ product.name }}">
                <div> <h4 class="card-mec-name">{{product.name}}</h4>  <p class="card-mec-price"><a class="fa fa-inr"></a> {{product.price}}</p>   </div>
        </div>
        </a>
    </div>
</div>
    {% empty %}
<div class="row mx_auto" >
    <p class="mx-auto text-center my_search_text">0 results found</p>
</div>
</div>


{% endfor %}
{% endblock %}